// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBexJKx_afjrVqddxpYIdSBg-hdER_SNOY',
    appId: '1:678434312658:web:7cf5c8a5e14283f7cf380b',
    messagingSenderId: '678434312658',
    projectId: 'flutter-chat-app-f0f18',
    authDomain: 'flutter-chat-app-f0f18.firebaseapp.com',
    storageBucket: 'flutter-chat-app-f0f18.appspot.com',
    measurementId: 'G-CGFVPWE8R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnRV3O-U4R5yB2pio8ETQvn_0WVEEDPS8',
    appId: '1:678434312658:android:537f1f452de7abe4cf380b',
    messagingSenderId: '678434312658',
    projectId: 'flutter-chat-app-f0f18',
    storageBucket: 'flutter-chat-app-f0f18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCNZGGP19SXfaHHmVunvy7REIGA9Jw7zY',
    appId: '1:678434312658:ios:dbfd550f6a40aac3cf380b',
    messagingSenderId: '678434312658',
    projectId: 'flutter-chat-app-f0f18',
    storageBucket: 'flutter-chat-app-f0f18.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCNZGGP19SXfaHHmVunvy7REIGA9Jw7zY',
    appId: '1:678434312658:ios:dbfd550f6a40aac3cf380b',
    messagingSenderId: '678434312658',
    projectId: 'flutter-chat-app-f0f18',
    storageBucket: 'flutter-chat-app-f0f18.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBexJKx_afjrVqddxpYIdSBg-hdER_SNOY',
    appId: '1:678434312658:web:9e33af789351877bcf380b',
    messagingSenderId: '678434312658',
    projectId: 'flutter-chat-app-f0f18',
    authDomain: 'flutter-chat-app-f0f18.firebaseapp.com',
    storageBucket: 'flutter-chat-app-f0f18.appspot.com',
    measurementId: 'G-TTFMSRXJY1',
  );
}
